clang-tidy currently (3.8) can do a lot of awesome changes. Don't run this batch file.

"clang-tidy.exe" -fix-errors -header-filter=^(?!.*(mini_boost)) -checks=*,-modernize-use-default libs\clipp\src\class.cpp -- -fms-compatibility-version=19 -I. -Imini_boost
"clang-tidy.exe" -fix-errors -header-filter=^(?!.*(mini_boost)) -checks=*,-modernize-use-default libs\clipp\src\container_wrapper.cpp -- -fms-compatibility-version=19 -I. -Imini_boost
"clang-tidy.exe" -fix-errors -header-filter=^(?!.*(mini_boost)) -checks=*,-modernize-use-default libs\clipp\src\context.cpp -- -fms-compatibility-version=19 -I. -Imini_boost
"clang-tidy.exe" -fix-errors -header-filter=^(?!.*(mini_boost)) -checks=*,-modernize-use-default libs\clipp\src\decorated_wrapper.cpp -- -fms-compatibility-version=19 -I. -Imini_boost
"clang-tidy.exe" -fix-errors -header-filter=^(?!.*(mini_boost)) -checks=*,-modernize-use-default libs\clipp\src\error_messages.cpp -- -fms-compatibility-version=19 -I. -Imini_boost
"clang-tidy.exe" -fix-errors -header-filter=^(?!.*(mini_boost)) -checks=*,-modernize-use-default libs\clipp\src\from_value.cpp -- -fms-compatibility-version=19 -I. -Imini_boost
"clang-tidy.exe" -fix-errors -header-filter=^(?!.*(mini_boost)) -checks=*,-modernize-use-default libs\clipp\src\member.cpp -- -fms-compatibility-version=19 -I. -Imini_boost
"clang-tidy.exe" -fix-errors -header-filter=^(?!.*(mini_boost)) -checks=*,-modernize-use-default libs\clipp\src\member_constructor.cpp -- -fms-compatibility-version=19 -I. -Imini_boost
"clang-tidy.exe" -fix-errors -header-filter=^(?!.*(mini_boost)) -checks=*,-modernize-use-default libs\clipp\src\member_function.cpp -- -fms-compatibility-version=19 -I. -Imini_boost
"clang-tidy.exe" -fix-errors -header-filter=^(?!.*(mini_boost)) -checks=*,-modernize-use-default libs\clipp\src\member_overloader.cpp -- -fms-compatibility-version=19 -I. -Imini_boost
"clang-tidy.exe" -fix-errors -header-filter=^(?!.*(mini_boost)) -checks=*,-modernize-use-default libs\clipp\src\member_property.cpp -- -fms-compatibility-version=19 -I. -Imini_boost
"clang-tidy.exe" -fix-errors -header-filter=^(?!.*(mini_boost)) -checks=*,-modernize-use-default libs\clipp\src\member_property_wrapper.cpp -- -fms-compatibility-version=19 -I. -Imini_boost
"clang-tidy.exe" -fix-errors -header-filter=^(?!.*(mini_boost)) -checks=*,-modernize-use-default libs\clipp\src\member_table.cpp -- -fms-compatibility-version=19 -I. -Imini_boost
"clang-tidy.exe" -fix-errors -header-filter=^(?!.*(mini_boost)) -checks=*,-modernize-use-default libs\clipp\src\member_wrapper.cpp -- -fms-compatibility-version=19 -I. -Imini_boost
"clang-tidy.exe" -fix-errors -header-filter=^(?!.*(mini_boost)) -checks=*,-modernize-use-default libs\clipp\src\object.cpp -- -fms-compatibility-version=19 -I. -Imini_boost
"clang-tidy.exe" -fix-errors -header-filter=^(?!.*(mini_boost)) -checks=*,-modernize-use-default libs\clipp\src\scope.cpp -- -fms-compatibility-version=19 -I. -Imini_boost
"clang-tidy.exe" -fix-errors -header-filter=^(?!.*(mini_boost)) -checks=*,-modernize-use-default libs\clipp\src\self.cpp -- -fms-compatibility-version=19 -I. -Imini_boost
"clang-tidy.exe" -fix-errors -header-filter=^(?!.*(mini_boost)) -checks=*,-modernize-use-default libs\clipp\src\type_id.cpp -- -fms-compatibility-version=19 -I. -Imini_boost
"clang-tidy.exe" -fix-errors -header-filter=^(?!.*(mini_boost)) -checks=*,-modernize-use-default libs\clipp\src\value.cpp -- -fms-compatibility-version=19 -I. -Imini_boost
"clang-tidy.exe" -fix-errors -header-filter=^(?!.*(mini_boost)) -checks=*,-modernize-use-default libs\clipp\test\test1\javascript_ast.cpp -- -fms-compatibility-version=19 -I. -Imini_boost
"clang-tidy.exe" -fix-errors -header-filter=^(?!.*(mini_boost)) -checks=*,-modernize-use-default libs\examples\array_test.cpp -- -fms-compatibility-version=19 -I. -Imini_boost
"clang-tidy.exe" -fix-errors -header-filter=^(?!.*(mini_boost)) -checks=*,-modernize-use-default libs\examples\automatic_semicolon.cpp -- -fms-compatibility-version=19 -I. -Imini_boost
"clang-tidy.exe" -fix-errors -header-filter=^(?!.*(mini_boost)) -checks=*,-modernize-use-default libs\examples\class_syntax.cpp -- -fms-compatibility-version=19 -I. -Imini_boost
"clang-tidy.exe" -fix-errors -header-filter=^(?!.*(mini_boost)) -checks=*,-modernize-use-default libs\examples\complex_test.cpp -- -fms-compatibility-version=19 -I. -Imini_boost
"clang-tidy.exe" -fix-errors -header-filter=^(?!.*(mini_boost)) -checks=*,-modernize-use-default libs\examples\enum_test.cpp -- -fms-compatibility-version=19 -I. -Imini_boost
"clang-tidy.exe" -fix-errors -header-filter=^(?!.*(mini_boost)) -checks=*,-modernize-use-default libs\examples\free_functions.cpp -- -fms-compatibility-version=19 -I. -Imini_boost
"clang-tidy.exe" -fix-errors -header-filter=^(?!.*(mini_boost)) -checks=*,-modernize-use-default libs\examples\global_test.cpp -- -fms-compatibility-version=19 -I. -Imini_boost
"clang-tidy.exe" -fix-errors -header-filter=^(?!.*(mini_boost)) -checks=*,-modernize-use-default libs\examples\iterative_statements.cpp -- -fms-compatibility-version=19 -I. -Imini_boost
"clang-tidy.exe" -fix-errors -header-filter=^(?!.*(mini_boost)) -checks=*,-modernize-use-default libs\examples\javascript_function.cpp -- -fms-compatibility-version=19 -I. -Imini_boost
"clang-tidy.exe" -fix-errors -header-filter=^(?!.*(mini_boost)) -checks=*,-modernize-use-default libs\examples\operator_test.cpp -- -fms-compatibility-version=19 -I. -Imini_boost
"clang-tidy.exe" -fix-errors -header-filter=^(?!.*(mini_boost)) -checks=*,-modernize-use-default libs\examples\switch_test.cpp -- -fms-compatibility-version=19 -I. -Imini_boost
"clang-tidy.exe" -fix-errors -header-filter=^(?!.*(mini_boost)) -checks=*,-modernize-use-default libs\examples\with_test.cpp -- -fms-compatibility-version=19 -I. -Imini_boost
"clang-tidy.exe" -fix-errors -header-filter=^(?!.*(mini_boost)) -checks=*,-modernize-use-default libs\examples\wrap_polymorphic_class.cpp -- -fms-compatibility-version=19 -I. -Imini_boost
"clang-tidy.exe" -fix-errors -header-filter=^(?!.*(mini_boost)) -checks=*,-modernize-use-default libs\examples\introduction\introduction.cpp -- -fms-compatibility-version=19 -I. -Imini_boost
"clang-tidy.exe" -fix-errors -header-filter=^(?!.*(mini_boost)) -checks=*,-modernize-use-default libs\javascript\src\array.cpp -- -fms-compatibility-version=19 -I. -Imini_boost
"clang-tidy.exe" -fix-errors -header-filter=^(?!.*(mini_boost)) -checks=*,-modernize-use-default libs\javascript\src\boolean.cpp -- -fms-compatibility-version=19 -I. -Imini_boost
"clang-tidy.exe" -fix-errors -header-filter=^(?!.*(mini_boost)) -checks=*,-modernize-use-default libs\javascript\src\complex.cpp -- -fms-compatibility-version=19 -I. -Imini_boost
"clang-tidy.exe" -fix-errors -header-filter=^(?!.*(mini_boost)) -checks=*,-modernize-use-default libs\javascript\src\date.cpp -- -fms-compatibility-version=19 -I. -Imini_boost
"clang-tidy.exe" -fix-errors -header-filter=^(?!.*(mini_boost)) -checks=*,-modernize-use-default libs\javascript\src\deterministic_parser.cpp -- -fms-compatibility-version=19 -I. -Imini_boost
"clang-tidy.exe" -fix-errors -header-filter=^(?!.*(mini_boost)) -checks=*,-modernize-use-default libs\javascript\src\global.cpp -- -fms-compatibility-version=19 -I. -Imini_boost
"clang-tidy.exe" -fix-errors -header-filter=^(?!.*(mini_boost)) -checks=*,-modernize-use-default libs\javascript\src\javascript_parser.cpp -- -fms-compatibility-version=19 -I. -Imini_boost
"clang-tidy.exe" -fix-errors -header-filter=^(?!.*(mini_boost)) -checks=*,-modernize-use-default libs\javascript\src\js_function.cpp -- -fms-compatibility-version=19 -I. -Imini_boost
"clang-tidy.exe" -fix-errors -header-filter=^(?!.*(mini_boost)) -checks=*,-modernize-use-default libs\javascript\src\js_function_init.cpp -- -fms-compatibility-version=19 -I. -Imini_boost
"clang-tidy.exe" -fix-errors -header-filter=^(?!.*(mini_boost)) -checks=*,-modernize-use-default libs\javascript\src\js_object.cpp -- -fms-compatibility-version=19 -I. -Imini_boost
"clang-tidy.exe" -fix-errors -header-filter=^(?!.*(mini_boost)) -checks=*,-modernize-use-default libs\javascript\src\js_string.cpp -- -fms-compatibility-version=19 -I. -Imini_boost
"clang-tidy.exe" -fix-errors -header-filter=^(?!.*(mini_boost)) -checks=*,-modernize-use-default libs\javascript\src\math.cpp -- -fms-compatibility-version=19 -I. -Imini_boost
"clang-tidy.exe" -fix-errors -header-filter=^(?!.*(mini_boost)) -checks=*,-modernize-use-default libs\javascript\src\null.cpp -- -fms-compatibility-version=19 -I. -Imini_boost
"clang-tidy.exe" -fix-errors -header-filter=^(?!.*(mini_boost)) -checks=*,-modernize-use-default libs\javascript\src\number.cpp -- -fms-compatibility-version=19 -I. -Imini_boost
"clang-tidy.exe" -fix-errors -header-filter=^(?!.*(mini_boost)) -checks=*,-modernize-use-default libs\javascript\src\parser_expressions.cpp -- -fms-compatibility-version=19 -I. -Imini_boost
"clang-tidy.exe" -fix-errors -header-filter=^(?!.*(mini_boost)) -checks=*,-modernize-use-default libs\javascript\src\parser_grammar1.cpp -- -fms-compatibility-version=19 -I. -Imini_boost
"clang-tidy.exe" -fix-errors -header-filter=^(?!.*(mini_boost)) -checks=*,-modernize-use-default libs\javascript\src\parser_grammar2.cpp -- -fms-compatibility-version=19 -I. -Imini_boost
"clang-tidy.exe" -fix-errors -header-filter=^(?!.*(mini_boost)) -checks=*,-modernize-use-default libs\javascript\src\parser_grammar3.cpp -- -fms-compatibility-version=19 -I. -Imini_boost
"clang-tidy.exe" -fix-errors -header-filter=^(?!.*(mini_boost)) -checks=*,-modernize-use-default libs\javascript\src\parser_grammar4.cpp -- -fms-compatibility-version=19 -I. -Imini_boost
"clang-tidy.exe" -fix-errors -header-filter=^(?!.*(mini_boost)) -checks=*,-modernize-use-default libs\javascript\src\parser_grammar5.cpp -- -fms-compatibility-version=19 -I. -Imini_boost
"clang-tidy.exe" -fix-errors -header-filter=^(?!.*(mini_boost)) -checks=*,-modernize-use-default libs\javascript\src\parser_grammar6.cpp -- -fms-compatibility-version=19 -I. -Imini_boost
"clang-tidy.exe" -fix-errors -header-filter=^(?!.*(mini_boost)) -checks=*,-modernize-use-default libs\javascript\src\parser_grammar7.cpp -- -fms-compatibility-version=19 -I. -Imini_boost
"clang-tidy.exe" -fix-errors -header-filter=^(?!.*(mini_boost)) -checks=*,-modernize-use-default libs\javascript\src\parser_grammar8.cpp -- -fms-compatibility-version=19 -I. -Imini_boost
"clang-tidy.exe" -fix-errors -header-filter=^(?!.*(mini_boost)) -checks=*,-modernize-use-default libs\javascript\src\parser_grammar9.cpp -- -fms-compatibility-version=19 -I. -Imini_boost
"clang-tidy.exe" -fix-errors -header-filter=^(?!.*(mini_boost)) -checks=*,-modernize-use-default libs\javascript\src\parser_literals.cpp -- -fms-compatibility-version=19 -I. -Imini_boost
"clang-tidy.exe" -fix-errors -header-filter=^(?!.*(mini_boost)) -checks=*,-modernize-use-default libs\javascript\src\parser_main.cpp -- -fms-compatibility-version=19 -I. -Imini_boost
"clang-tidy.exe" -fix-errors -header-filter=^(?!.*(mini_boost)) -checks=*,-modernize-use-default libs\javascript\src\parser_statements.cpp -- -fms-compatibility-version=19 -I. -Imini_boost
"clang-tidy.exe" -fix-errors -header-filter=^(?!.*(mini_boost)) -checks=*,-modernize-use-default libs\javascript\src\parser_symbols.cpp -- -fms-compatibility-version=19 -I. -Imini_boost
"clang-tidy.exe" -fix-errors -header-filter=^(?!.*(mini_boost)) -checks=*,-modernize-use-default libs\javascript\src\primitive.cpp -- -fms-compatibility-version=19 -I. -Imini_boost
"clang-tidy.exe" -fix-errors -header-filter=^(?!.*(mini_boost)) -checks=*,-modernize-use-default libs\javascript\src\reference.cpp -- -fms-compatibility-version=19 -I. -Imini_boost
"clang-tidy.exe" -fix-errors -header-filter=^(?!.*(mini_boost)) -checks=*,-modernize-use-default libs\javascript\src\undefined.cpp -- -fms-compatibility-version=19 -I. -Imini_boost
"clang-tidy.exe" -fix-errors -header-filter=^(?!.*(mini_boost)) -checks=*,-modernize-use-default libs\javascript\src\compiler\date_impl.cpp -- -fms-compatibility-version=19 -I. -Imini_boost
